((nil . ((css-indent-offset . 2)
         (js-indent-level . 2)
         (eglot-server-programs . (((css-mode css-ts-mode) . ("vscode-css-language-server" "--stdio"))
                                   (((js-mode :language-id "javascript")
                                     (js-ts-mode :language-id "javascript")
                                     (tsx-ts-mode :language-id "typescriptreact")
                                     (typescript-ts-mode :language-id "typescript")
                                     (typescript-mode :language-id "typescript"))
                                    . ("typescript-language-server" "--stdio"))
                                   ((js-json-mode json-mode json-ts-mode jsonc-mode)
                                    . ("vscode-json-language-server" "--stdio"))
                                   (org-mode . ("harper-ls" "--stdio")))))))
