#+TITLE: Publishing Org-mode files to HTML
#+DATE: <2019-12-01 Sun 23:03>

#+BEGIN_QUOTE
Emacs is the best editor in the world.
#+END_QUOTE

This is a guide to describe how to publish Org mode files to HTML.

* Basics

Create your blog files and css files.

#+begin_details
#+begin_summary
Example of file directory structure
#+end_summary

#+begin_src shell
~/blog/org/
   |- css/
   |  `- worg.css
   |- img/
   |- index.org
   `- remember.org
#+end_src
#+end_details

* Publishing the org project

#+begin_details
#+begin_summary
Configuration of =org-publish-project-alist=
#+end_summary

#+begin_src emacs-lisp
(setq org-publish-project-alist
      '(;; Publish the posts
        ("blog-notes"
         :base-directory "~/blog/org"
         :base-extension "org"
         :publishing-directory "~/blog/public"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :section-numbers nil
         :with-author nil
         :with-creator nil
         :with-email nil
         :with-timestamps nil
         :auto-preamble t
         ; :auto-postamble nil
         :html-head "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/worg.css\"/>"
         :html-head-include-default-style nil
         ; :html-head-include-scripts nil
         ; :html-preamble nil
         ; :html-postamble nil
         :html-link-home "index.html"
         :html-link-up "sitemap.html"
         :html-metadata-timestamp-format "%Y-%m-%d %H:%M"
         :htmlized-source t
         :auto-sitemap t
         :sitemap-filename "sitemap.org"
         :sitemap-title "Sitemap")

        ;; For static files that should remain untouched
        ("blog-static"
         :base-directory "~/blog/org"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf\\|eot\\|svg\\|woff\\|woff2\\|ttf"
         :publishing-directory "~/blog/public"
         :recursive t
         :publishing-function org-publish-attachment)

        ;; Combine the two previous components in a single one
        ("blog" :components ("blog-notes" "blog-static"))))
#+end_src
#+end_details

Then run =org-publish-project= to generate html files to =~/blog/public= folder.

* Update

- 2023-05-22 Put all org publish configurations in [[https://github.com/xuchengpeng/.emacs.d/blob/main/lisp/init-org.el][init-org.el]].
- 2023-12-27 Add head, header and footer options.
- 2023-12-28 Export with HTML5 and toc by default.
- 2024-12-25 Add default meta description and keywords.
- 2024-12-27 Export with stable IDs and preview contents.
- 2024-12-31 Remove preview contents.
- 2025-01-03 Prefer HTML5 semantic elements.
- 2025-01-06 Export the CSS selectors only.
- 2025-01-07 Publish head, header and footer from HTML assets.
- 2025-01-08 Export checkbox with html type.
- 2025-01-27 Include chinese characters while generating stable IDs.
- 2025-02-05 Remove default meta description and keywords, customize meta tags in post files.

#+include: ../comments.inc
