#+TITLE: Emacs tokyonight-themes
#+DATE: <2024-02-01 Thu 08:28>

#+begin_quote
A clean dark Visual Studio Code theme that celebrates the lights of Downtown [[https://www.google.com/search?q=tokyo+night&newwindow=1&sxsrf=ACYBGNRiOGCstG_Xohb8CgG5UGwBRpMIQg:1571032079139&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiayIfIhpvlAhUGmuAKHbfRDaIQ_AUIEigB&biw=1280&bih=666&dpr=2][Tokyo at night]].
#+end_quote

Tokyo Night theme was firstly published as a plugin for Visual Studio Code, now it has many [[https://github.com/enkia/tokyo-night-vscode-theme#other-ports][other ports]].

Rawley make a [[https://github.com/rawleyfowler/tokyo-theme.el][tokyo-theme.el]] for GNU Emacs, but it is unmaintained and has not support any popular packages for GNU Emacs we often use.

So I want to make it for myself, [[https://github.com/xuchengpeng/tokyonight-themes][here it is]]. The theme templates were taken from [[https://github.com/protesilaos/modus-themes][modus-themes]], and the color palettes were taken from [[https://github.com/folke/tokyonight.nvim][tokyonight.nvim]], these two themes are very popular and awesome with GNU Emacs or [[https://github.com/neovim/neovim][Neovim]].

This theme has four color palettes, as same sa tokyonight.nvim. I have add support with some popular packages which I often use with GNU Emacs, like Corfu, vertico, orderless, dired, diff-hl, hl-todo, multiple-cursors, symbol-overlay, vundo and so on.

If you like it, clone the theme, and add support for your plugins into the theme code. Also, you can use theme colors in code with ~tokyonight-themes-with-colors~.

For example, add support for git-gutter-fr package.

#+begin_src emacs-lisp
(tokyonight-themes-with-colors
  (custom-set-faces
    `(git-gutter-fr:added ((,c :foreground ,green)))
    `(git-gutter-fr:deleted ((,c :foreground ,red)))
    `(git-gutter-fr:modified ((,c :foreground ,yellow)))))
#+end_src

Evaluate the code with a function after the tokyonight-themes load.

If you want to change the color palettes, we have a option for palette overrides. Customize ~tokyonight-<style>-palette-overrides~ before you load the tokyonight-themes, style is an choice with ~storm~, ~moon~, ~night~ or ~day~.

For example, change the blue and cyan color for tokyonight-day-theme.

#+begin_src emacs-lisp
(setq tokyonight-day-palette-overrides
      '((blue . "#2e7de9")
        (cyan . "#007197")))
#+end_src

#+include: ../comments.inc
