#+TITLE: Emacs Proxy
#+AUTHOR: Chuck
#+DATE: <2024-02-05 Mon 08:20>
#+INCLUDE: ../org-macros.setup

Proxy servers are commonly used to provide gateways through firewalls or as caches serving some more-or-less local network. Each protocol (HTTP, FTP, etc.) can have a different gateway server. Proxying is conventionally configured commonly amongst different programs through environment variables of the form /protocol-proxy/, where /protocol/ is one of the supported network protocols (http, ftp, etc.). The library recognized such variables in either upper or lower case.

* System Proxy
:PROPERTIES:
:CUSTOM_ID: system-proxy
:END:

Add these lines to =.bashrc=:

#+begin_src bash
export http_proxy=http://username:password@proxy.xxx.com:8080
export https_proxy=${http_proxy}
#+end_src

Or add these lines to =init.el=:

#+begin_src emacs-lisp
(setenv "http_proxy" "http://user:pass@proxy.server:port")
(setenv "https_proxy" "https://user:pass@proxy.server:port")
(setenv "no_proxy" "localhost,127.0.0.1,.local")
#+end_src

* URL Proxy Services
:PROPERTIES:
:CUSTOM_ID: url-proxy-services
:END:

Proxies are supported by URL package, by setting ~url-proxy-services~ to an assoc list mapping url services and the proxy servers that support them.

#+begin_details
#+begin_summary
Customize =url-proxy-services=:
#+end_summary

#+begin_src emacs-lisp
(setq url-proxy-services
      '(("http"     . "proxy.example.com:8080")
        ("https"    . "proxy.example.com:8080")
        ("no_proxy" . "^.*example.com")))
#+end_src
#+end_details

If the proxy services need to be authorized, we need to customize ~url-http-proxy-basic-auth-storage~.

#+begin_details
#+begin_summary
Customize =url-http-proxy-basic-auth-storage=:
#+end_summary

#+begin_src emacs-lisp
(setq url-http-proxy-basic-auth-storage
      (list (list "proxy.example.com:8080"
                  (cons "Input your LDAP UID !"
                        (base64-encode-string "LOGIN:PASSWORD")))))
#+end_src
#+end_details

* Socks Proxy
:PROPERTIES:
:CUSTOM_ID: socks-proxy
:END:

#+begin_details
#+begin_summary
Enable socks proxy
#+end_summary

#+begin_src emacs-lisp
(setq url-gateway-method 'socks
      socks-server '("Default Server" "socks.proxy.com" 1080 5)
      socks-noproxy '("localhost"))
#+end_src
#+end_details

If the ~socks-server~ need to be authorized, ~socks-username~ and ~socks-password~ need to be customized.

#+begin_details
#+begin_summary
Disable socks proxy
#+end_summary

#+begin_src emacs-lisp
(setq url-gateway-method 'native
      socks-server nil
      socks-noproxy nil)
#+end_src
#+end_details

{{{post-meta}}}

#+include: ../comments.inc
