#+TITLE: Build Emacs From Source
#+AUTHOR: Chuck
#+DATE: <2024-03-08 Fri 15:36>
#+INCLUDE: ../org-macros.setup

Windows 11 features [[https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][built-in support for running Linux GUI applications]]. Emacs 29 has became a real GTK application, gone with the blurry fonts problem.

This is a guide to show how to build Emacs from source for Linux.

* Install Essential Packages

Firstly, install essential packages in WSL2 Ubuntu 22.04.

#+begin_src shell
apt-get update
apt-get install build-essential libgtk-3-dev libgnutls28-dev libtiff5-dev libgif-dev libjpeg-dev libpng-dev libxpm-dev libncurses-dev texinfo sqlite3 libsqlite3-dev libjansson4 libjansson-dev autoconf
#+end_src

Native compilation support is enabled by default with emacs 30, install =libgccjit0= and =libgccjit-xx-dev= to build this feature.

#+begin_src shell
apt-get install libgccjit0 libgccjit-13-dev
#+end_src

* Tree-sitter Support

And in Emacs 29, support for tree-sitter is built-in. Now build tree-sitter from source code.

#+begin_src shell
git clone https://github.com/tree-sitter/tree-sitter.git
cd tree-sitter
git checkout v0.24.6
make
make install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
#+end_src

Now tree-sitter library has been installed into =/usr/local/lib=.

* Install Emacs

Now build emacs with pgtk and tree-sitter.

#+begin_src shell
git clone https://git.savannah.gnu.org/git/emacs.git -b emacs-30
cd emacs
./autogen.sh
./configure --prefix=/usr/local/emacs --with-native-compilation=aot --with-pgtk --with-tree-sitter --without-pop
make -j 8
make install
#+end_src

* Install libvterm

Build [[https://www.leonerd.org.uk/code/libvterm/][libvterm]] if you need to use [[https://github.com/akermu/emacs-libvterm][vterm]] on Linux.

#+begin_src shell
tar -zxf libvterm-0.3.3.tar.gz
cd libvterm-0.3.3
make
make install
#+end_src

* FAQs

When run emacs with WSL Ubuntu 24.04, [[https://github.com/microsoft/wslg/issues/1244][Ubuntu 24.04 Wayland falling back to X11]].

Due to a bug of systemd fixed in 24.04, you must do:

#+begin_src shell
ln -sf /mnt/wslg/runtime-dir/wayland-* $XDG_RUNTIME_DIR/
#+end_src

Or use an autostart conf: https://github.com/viruscamp/wslg-links.

{{{post-meta}}}

#+include: ../comments.inc
