#+TITLE: 中医：五脏与五行
#+DATE: <2024-01-24 Wed 09:31>

中医腑脏[fn:1]通常成为五脏六腑。五脏是：肝、心、脾、肺、肾，主要功能为生化和蓄存精气；六腑是：胆、小肠、胃、大肠、膀胱、三焦[fn:2]，主要功能为受乘和传化水谷并积存精气。

《黄帝内经》中，五行与五脏相互对应，即心火、肝木、脾土、肺金、肾水。各脏器之间又相生相克。

相生：肝生心，心生脾，脾生肺，肺生肾，肾生肝。

相克：肝克脾，脾克肾，肾克心，心克肺，肺克肝。

- 心：《黄帝内经》说：“心者五脏六腑之大主”。主神志，主血脉，在液为汗，开窍于舌。位于胸腔之内，斜位于胸腔中纵隔内，隔膜之上，两肺之间，三分之二位于正中线左侧，三分之一位于正中线右侧，心尖朝向左前下方。形似倒垂未开之莲蕊，外有心包护卫。心为神之舍，血之主，脉之宗，在五行属火，为阳中之阳，起着主宰人体生命活动的作用。手少阴心经与手太阳小肠经在小肠与心之间相互络属， **与小肠相表里** 。

- 肝：在五行属木，主疏泄，魂之处，藏血，其华在爪，其充在筋，开窍于目，在志为怒，在液为泪， **与胆相表里** 。《素问》说：”肝者，将军之官，谋虑出焉”，表现在调节精神情志，促进消化吸收，以及维持气血、津液的运作三方面。肝位于上腹部，横隔之下。

- 脾：在五行属土，主藏，统血，谓之主，开窍于口，主肌肉，运化水谷，主升清，后天之本，主四肢，其华在唇，统血益气，在志为思，藏意生思，思伤脾。在液为涎；藏营，司运动， **与胃相表里** 。

- 肺：在五行属金，专司呼吸，主宣发速降，通调水道，朝百脉，主治节，协助心君调节气血运行，故称“相傅之官”。其附属功能为：在志为忧（悲），在液为涕，在体合皮，其华在毛，在窍为鼻。 **与大肠相表里** 。阳中为少阳，三焦为上焦。

- 肾：在五行属水，肾的主要功能是藏精，主生长发育和生殖；主水液、肾主纳气。与其它组织器官的关系是：肾主骨、生髓、通于脑，齿为骨之余。其华在发，开窍于耳及二阴，在志为恐，在液为唾。 **与膀胱相表里** 。

| 五行 | 五脏 | 六腑 | 季节 | 五情 | 五官 | 五味 | 五华 | 五音 | 五色 |
|-----+-----+-----+-----+-----+-----+-----+-----+-----+-----|
| 火   | 心   | 小肠 | 夏   | 喜   | 舌   | 苦   | 面   | 宫   | 红   |
| 木   | 肝   | 胆   | 春   | 怒   | 目   | 酸   | 爪   | 商   | 青   |
| 土   | 脾   | 胃   | 长夏 | 思   | 口   | 甜   | 唇   | 角   | 黄   |
| 金   | 肺   | 大肠 | 秋   | 悲   | 鼻   | 辣   | 皮毛 | 幑   | 白   |
| 水   | 肾   | 膀胱 | 冬   | 恐   | 耳   | 咸   | 发   | 羽   | 黑   |

[fn:1] 中医的腑脏，和西医提出的腑脏的生理结构并非相同。西医传入中国时，寻找了中医中结构相近的器官进行翻译，功能上不完全对应。
[fn:2] 三焦为六腑之一，又名”决渎之官”，为上焦、中焦、下焦三者的统称，对应的脏为心包。焦古作膲，为皮下、肌间纹理之意。

