#+TITLE: 读《未来简史》
#+DATE: <2025-01-02 Thu 10:59>

从智人到智神。

在减少了饥荒、疾病和战争之后，我们现在希望克服年老甚至战胜死亡。在拯救人类脱离各种不幸之后，我们现在希望他们能够幸福快乐。而在提升人性超越挣扎求生的动物性之后，我们现在希望把人类升级为神，让智人化身为智神。

知识的悖论。知识如果不能改变行为，就没有用处。但知识一旦改变了行为，本身就立刻失去意义。我们拥有越多数据，对历史了解越深入，历史的轨迹就改变的越快，我们的知识也过时得越快。

* 人类世
:PROPERTIES:
:CUSTOM_ID: anthropocene
:END:

算法指的是进行计算、解决问题、做出决定的一套有条理的步骤。所以，算法并不是单只某次计算，而是计算时采用的方法。控制自助饮料机的算法，是通过机械齿轮和电路来运作的。控制人类的算法，则通过感觉、情感和思想来运作。至于猪、狒狒、水獭和鸡，用的也是同一种算法。

《圣经》中的洪水故事成为农业世界的奠基神话。当然，我们也可以给它添上一点现代环保的色彩，说这场洪水是在教训人类，要我们知道人类的行为可能毁掉整个生态系统，而人类要负起保护万物的神圣使命。只是就传统诠释而言，洪水恰恰证明了人类的优越杰出以及动物的毫无价值。在传统诠释中，挪亚虽然奉命拯救了整个生态系统，但目的是保护神和人类的共同利益，而不是为了动物的利益。非人类的生物本身并没有价值，它们为了人类的利益而存在。

农业革命促成了有神论宗教，而科技革命则催生了人文主义宗教：以人取代了神。有神论者崇拜的是神，人文主义者则是崇拜人。人文主义的奠基概念认为智人拥有某些独特而神圣的本质，这些本质是宇宙间所有意义和全力的来源。宇宙间发生的所有事，都会以“对智人的影响”作为判断好坏的依据。

* 人类的特质
:PROPERTIES:
:CUSTOM_ID: human-traits
:END:

传统一神论会说，只有智人拥有永恒的灵魂。进化论无法解释灵魂的存在。进化就是变化，进化无法产生永恒不变的实体。从进化角度来看，我们最接近人类本质的就是我们的DNA，但DNA分子承载的绝非永恒，而是突变。但这让很多人害怕，宁可不信进化论，也不想放弃自己的灵魂。

另一种证明人比其他动物优越的理由，是说地球上所有的动物中，只有智人拥有心灵。心灵和灵魂大不相同。心灵并不是神秘而永恒的概念，也不是像眼睛或大脑之类的器官，而是脑中主观体验（例如痛苦、快乐、愤怒和爱）的流动。心灵与永恒的灵魂不同，心灵可以分成许多部分，又不断变动，而且没有理由认为心灵是永恒的。

意识可能就是在复杂的神经网络信号传送之后造成的心理污染，没有任何功用，就是存在那里罢了。如果确实如此，也就是说这几百万年来，几十亿生物所经历的痛苦和快乐只是一种心理污染。这绝对是个值得思考的想法，虽然可能并不正确。

[[https://en.wikipedia.org/wiki/Turing_test][图灵测试]]其实就是复制了每个同性恋男子在1950年英国必须通过的日常测试：你能装成一个异性恋吗？图灵从自己的个人经验就知道，你究竟是谁根本不重要，重要的是别人对你的看法。而根据图灵的看法，未来的计算机就像20世纪50年代的男同性恋者，计算机究竟有没有意识并不重要，重要的是人类会怎么想。

人类自己也常常在不用言语表达的情况下，意识到过去和未来的事件。特别是在梦境里，我们可以不用语言就了解整个叙事情境，而醒过来之后要用语言重述却变得非常困难。

我们征服世界的关键因素，其实在于让许多人类团结起来的能力。如今人类完全主宰地球，并不是因为单个人比单个黑猩猩或狼更聪明，或是手指更灵巧，而是地球上只有智人这个物种能够大规模而灵活地合作。智力和制造工具当然非常重要，但如果人类还没学会如何大规模灵活合作，大脑再聪明、手脚再灵活，到现在也仍然是在敲燧石，而不是撞击铀原子。

研究指出，不论是朋友还是敌人，智能能够真正熟识的对象不超过150人。不管人类靠什么打造出了大规模合作网络，总之绝不是仅靠个人熟识而已。[[https://en.wikipedia.org/wiki/Ultimatum_game][最后通牒博弈]]影响深远，不仅动摇了古典经济学理论，也建立起近几十年最重要的一项经济学发现：智人的行事并不是依照冰冷冷的数学逻辑，而是根据有温度的社交逻辑。我们受情感控制。所有大规模人类合作，到头来都是基于我们想象的秩序。这一套又一套的规矩，虽然只存在于我们的想象之中，我们却会认为这就像重力一样真实而不可侵犯。只要智人住在相信同样一套故事的地方，就会遵守一样的规矩，于是不仅很容易预测陌生人会有什么行为，也很方便组织大规模合作的网络。智人也常常用可见的标记（例如头巾、胡子或西装）来代表“你可以信任我，因为我跟你信的故事是一样的”。

人之所以很难理解“想象的秩序”这种概念，是因为人觉得现实只有两类：客观现实和主观现实。所谓客观现实，就是事物的存在与我们的信念和感受无关。相反，主观现实取决于个人的信念和感受。然而，现实还有第三个层次：互为主体。这种互为主体的现实，并不是因为个人的信念或感受而存在，而是依靠许多人类的沟通互动而存在。历史上有许多最重要的驱动因素，都具有互为主体的概念。例如金钱的价值、法律、神，甚至是整个帝国。

智人统治世界，是因为只有智人能够编织出互为主体的意义之网：其中的法律、约束力、实体和地点都只存在于他们共同的想象之中。这张网，让所有动物中只有人类能够组织十字军、革命和人权运动。

* 虚构的力量
:PROPERTIES:
:CUSTOM_ID: the-power-of-fiction
:END:

人类认为自己创造了历史，但历史其实是围绕着各种虚构故事展开的。单一人类个体的基本能力，从石器时代依赖并没有多大改变，真要说有什么改变，也可能只是在衰退。但是各种虚构故事的力量在增强，它们推动了历史，让我们从石器时代走到了硅时代。

在没有文字的社会里，人类通过大脑完成所有计算，做出所有决定；而有了文字之后，人类就能组成网络，每个人完成庞大算法里的一个小步骤，而最后的重要决定由整个算法做出。这正是官僚体系的本质。

林肯就说过，你不可能在所有的时候骗过所有人。只不过，那是林肯一厢情愿罢了。实际上，人类合作网络的力量就是依赖于真实与虚构之间的微妙平衡。太过扭曲现实，力量就会被削弱，让你敌不过那些能看清现实的对手；但想要有效壮大组织力量，仍然得依靠那些虚构得神话。如果坚持一切都要百分之百的现实、绝不加入任何虚构，追随者肯定也不会太多。

虚构故事能让人类更容易合作，但代价在于，这些虚构故事同时也会决定我们合作的目标。因此，我们可能拥有非常复杂的合作制度，却只是为了服务于虚构的目标和利益。这样一来，虽然整个制度看起来运转良好，但出发点可能只是这个制度的标准。

#+include: ../comments.inc
