#+TITLE: 读《未来简史》
#+DATE: <2025-01-02 Thu 10:59>

从智人到智神。

在减少了饥荒、疾病和战争之后，我们现在希望克服年老甚至战胜死亡。在拯救人类脱离各种不幸之后，我们现在希望他们能够幸福快乐。而在提升人性超越挣扎求生的动物性之后，我们现在希望把人类升级为神，让智人化身为智神。

知识的悖论。知识如果不能改变行为，就没有用处。但知识一旦改变了行为，本身就立刻失去意义。我们拥有越多数据，对历史了解越深入，历史的轨迹就改变的越快，我们的知识也过时得越快。

* 人类世
:PROPERTIES:
:CUSTOM_ID: anthropocene
:END:

算法指的是进行计算、解决问题、做出决定的一套有条理的步骤。所以，算法并不是单只某次计算，而是计算时采用的方法。控制自助饮料机的算法，是通过机械齿轮和电路来运作的。控制人类的算法，则通过感觉、情感和思想来运作。至于猪、狒狒、水獭和鸡，用的也是同一种算法。

《圣经》中的洪水故事成为农业世界的奠基神话。当然，我们也可以给它添上一点现代环保的色彩，说这场洪水是在教训人类，要我们知道人类的行为可能毁掉整个生态系统，而人类要负起保护万物的神圣使命。只是就传统诠释而言，洪水恰恰证明了人类的优越杰出以及动物的毫无价值。在传统诠释中，挪亚虽然奉命拯救了整个生态系统，但目的是保护神和人类的共同利益，而不是为了动物的利益。非人类的生物本身并没有价值，它们为了人类的利益而存在。

农业革命促成了有神论宗教，而科技革命则催生了人文主义宗教：以人取代了神。有神论者崇拜的是神，人文主义者则是崇拜人。人文主义的奠基概念认为智人拥有某些独特而神圣的本质，这些本质是宇宙间所有意义和全力的来源。宇宙间发生的所有事，都会以“对智人的影响”作为判断好坏的依据。

* 人类的特质
:PROPERTIES:
:CUSTOM_ID: human-traits
:END:

传统一神论会说，只有智人拥有永恒的灵魂。进化论无法解释灵魂的存在。进化就是变化，进化无法产生永恒不变的实体。从进化角度来看，我们最接近人类本质的就是我们的DNA，但DNA分子承载的绝非永恒，而是突变。但这让很多人害怕，宁可不信进化论，也不想放弃自己的灵魂。

另一种证明人比其他动物优越的理由，是说地球上所有的动物中，只有智人拥有心灵。心灵和灵魂大不相同。心灵并不是神秘而永恒的概念，也不是像眼睛或大脑之类的器官，而是脑中主观体验（例如痛苦、快乐、愤怒和爱）的流动。心灵与永恒的灵魂不同，心灵可以分成许多部分，又不断变动，而且没有理由认为心灵是永恒的。

意识可能就是在复杂的神经网络信号传送之后造成的心理污染，没有任何功用，就是存在那里罢了。如果确实如此，也就是说这几百万年来，几十亿生物所经历的痛苦和快乐只是一种心理污染。这绝对是个值得思考的想法，虽然可能并不正确。

[[https://en.wikipedia.org/wiki/Turing_test][图灵测试]]其实就是复制了每个同性恋男子在1950年英国必须通过的日常测试：你能装成一个异性恋吗？图灵从自己的个人经验就知道，你究竟是谁根本不重要，重要的是别人对你的看法。而根据图灵的看法，未来的计算机就像20世纪50年代的男同性恋者，计算机究竟有没有意识并不重要，重要的是人类会怎么想。

#+include: ../comments.inc
