#+BEGIN_EXPORT html
<div class="giscus-comments">
  <br>
  <script src="https://giscus.app/client.js"
    data-repo="xuchengpeng/xuchengpeng.github.io"
    data-repo-id="R_kgDONhnKaQ"
    data-category="Comments"
    data-category-id="DIC_kwDONhnKac4CmRAA"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="en"
    data-loading="lazy"
    crossorigin="anonymous"
    async>
  </script>
</div>
#+END_EXPORT
